### PR TITLE
Redirecting to wiki

### PR DESCRIPTION
**Pull request by garethfoote**

### CODE REVIEW

**Review by MancunianSam — APPROVED** [review]

**Comment by TomJKing** [comment]
@garethfoote Can these changes be merged? If not maybe this PR can be closed as its been open for a while.

**Comment by MancunianSam** [comment]
Also @garethfoote if this is no longer used, can we archive this repository? It'll still be available for read only but it would stop dependabot trying to update it.

**Comment by garethfoote** [comment]
Hi @TomJKing and @MancunianSam Until something better comes along I'm going to use the [wiki](https://github.com/nationalarchives/tdr-design-documentation/wiki) for design documentation.

**Comment by MancunianSam** [comment]
@garethfoote Yeah, you can merge this and we'll keep the repo open so you can use the wiki.

**Pull request merged**
